languageCode = "en-us"
title = "知行合一"
baseurl = "https://jackypanster.github.io/blog/"
theme = "bootie-docs"
copyright = "Copyright (c) 2017, Jacky Pan; All rights reserved."

[params]
  description = "知是行之始，行是知之成。若会得时，只说一个知，已自有行在。只说一个行，已自有知在。"
  withSitePosts = true
  searchDomain = "jackypanster.github.io"
  noCategoryLink = true
  repositoryUrl = "https://jackypanster.github.io/blog/"
  highlightStyle = "github"

[[params.mainMenu]]
  name = "Book"
  link = "book/"

#[[params.mainMenu]]
  #name = "Usage"
  #link = "usage/"

[[params.mainMenu]]
  name = "Quant"
  link = "quant/"

[[params.mainMenu]]
  name = "Travel"
  link = "travel/"